[package]
name = "base_url"
version = "0.0.5"
authors = ["Brady McDonough <brady.mcd.codes@gmail.com>"]
repository = "https://github.com/bradymcd/rs-baseurl"
lisence = "MIT"
description = "A Url type which strictly cuts out errors related to parsing and host suitability after creation at the cost of some flexibility"


[dependencies]
url="1.7.0"
try_from="0.2.2"