[package]
name = "base_url"
description = "A Url type which strictly cuts out errors related to parsing and host suitability after creation at the cost of some flexibility"
authors = ["Brady McDonough <brady.mcd.codes@gmail.com>"]
repository = "https://github.com/bradymcd/rs-baseurl"
license = "MIT"
version = "0.0.8"


[dependencies]
url = "^1.0.0"
try_from = "0.2.2"

[dependencies.robotparser]
version = "^0.10.1"
optional = true

[dependencies.sitemaps]
version = "^0.3.0"
optional = true

[features]
default = []
robot_conversion = ["robotparser", "_conversion_any"]
sitemap_conversion = ["sitemaps", "_conversion_any"]
_conversion_any = [] ##Internal use only